version: '3'
services:
  plantuml-server:
    container_name: drawio-plantuml
    image: jgraph/plantuml-server
    volumes:
      - ./fonts:/usr/share/fonts/drawio
    restart: unless-stopped
    networks:
      - internal

  image-export:
    container_name: drawio-export
    image: jgraph/export-server
    volumes:
      - ./fonts:/usr/share/fonts/drawio
    restart: unless-stopped
    networks:
      - internal
    environment:
      - DRAWIO_SERVER_URL=${DRAWIO_BASE_URL}

  drawio:
    container_name: drawio
    image: jgraph/drawio
    restart: unless-stopped
    depends_on:
      - plantuml-server
      - image-export
    networks:
      - internal
      - proxy
    environment:
      - DRAWIO_SELF_CONTAINED=1
      - PLANTUML_URL=http://drawio-plantuml:8080/
      - EXPORT_URL=http://drawio-export:8000/
      - DRAWIO_BASE_URL=${DRAWIO_BASE_URL}
      - DRAWIO_VIEWER_URL=${DRAWIO_VIEWER_URL}
      - DRAWIO_LIGHTBOX_URL=${DRAWIO_LIGHTBOX_URL}
      - DRAWIO_CSP_HEADER=${DRAWIO_CSP_HEADER}
      - DRAWIO_CONFIG=${DRAWIO_CONFIG}
      - DRAWIO_GOOGLE_CLIENT_ID=${DRAWIO_GOOGLE_CLIENT_ID}
      - DRAWIO_GOOGLE_APP_ID=${DRAWIO_GOOGLE_APP_ID}
      - DRAWIO_GOOGLE_CLIENT_SECRET=${DRAWIO_GOOGLE_CLIENT_SECRET}
      - DRAWIO_GOOGLE_VIEWER_CLIENT_ID=${DRAWIO_GOOGLE_VIEWER_CLIENT_ID}
      - DRAWIO_GOOGLE_VIEWER_APP_ID=${DRAWIO_GOOGLE_VIEWER_APP_ID}
      - DRAWIO_GOOGLE_VIEWER_CLIENT_SECRET=${DRAWIO_GOOGLE_VIEWER_CLIENT_SECRET}
      - DRAWIO_MSGRAPH_CLIENT_ID=${DRAWIO_MSGRAPH_CLIENT_ID}
      - DRAWIO_MSGRAPH_CLIENT_SECRET=${DRAWIO_MSGRAPH_CLIENT_SECRET}
      - DRAWIO_GITLAB_ID=${DRAWIO_GITLAB_ID}
      - DRAWIO_GITLAB_URL=${DRAWIO_GITLAB_URL}
      - DRAWIO_CLOUD_CONVERT_APIKEY=${DRAWIO_CLOUD_CONVERT_APIKEY}
      - DRAWIO_CACHE_DOMAIN=${DRAWIO_CACHE_DOMAIN}
      - DRAWIO_MEMCACHED_ENDPOINT=${DRAWIO_MEMCACHED_ENDPOINT}
      - DRAWIO_PUSHER_MODE=2
      - DRAWIO_IOT_ENDPOINT=${DRAWIO_IOT_ENDPOINT}
      - DRAWIO_IOT_CERT_PEM=${DRAWIO_IOT_CERT_PEM}
      - DRAWIO_IOT_PRIVATE_KEY=${DRAWIO_IOT_PRIVATE_KEY}
      - DRAWIO_IOT_ROOT_CA=${DRAWIO_IOT_ROOT_CA}
      - DRAWIO_MXPUSHER_ENDPOINT=${DRAWIO_MXPUSHER_ENDPOINT}

networks:
  proxy:
    external: true
    name: proxy
  internal:
    internal: true
    driver: bridge
