version: "2.1"
services:

  resilio-sync:
    container_name: resilio-sync
    image: ghcr.io/linuxserver/resilio-sync
    environment:
      - TZ=Etc/UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./sync:/sync
    ports:
      - 55555:55555
    restart: unless-stopped
    networks:
      - external

networks:
  external:
    name: resilio-sync_external
