version: "2.1"
services:

  hedgedoc:
    container_name: hedgedoc
    image: linuxserver/hedgedoc:latest
    volumes:
      - ./data/app:/config
    restart: unless-stopped
    depends_on:
      - hedgedoc-db
    environment:
      - TZ=Etc/UTC
      - DB_HOST=hedgedoc-db
      - DB_PORT=3306
      - DB_NAME=hedgedoc
      - DB_USER=hedgedoc
      - DB_PASS=${MYSQL_PASSWORD}
      - CMD_DOMAIN=${CMD_DOMAIN}
      - CMD_HOST=hedgedoc
      - CMD_PROTOCOL_USESSL=true
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_ALLOW_FREEURL=true
      - CMD_REQUIRE_FREEURL_AUTHENTICATION=true
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_DEFAULT_PERMISSION=private
    networks:
      - external
      - internal

  hedgedoc-db:
    container_name: hedgedoc-db
    image: linuxserver/mariadb:latest
    volumes:
      - ./data/db:/config
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - internal

networks:
  external:
    name: hedgedoc_external
  internal:
    name: hedgedoc_internal
    internal: true
