version: "2.1"
services:
  app:
    container_name: hedgedoc
    image: linuxserver/hedgedoc:latest
    volumes:
      - ./config/app:/config
    restart: unless-stopped
    networks:
      - proxy
      - internal
    environment:
      - TZ=Etc/UTC
#     - PGID=1000
#     - PUID=1000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=hedgedoc
      - DB_USER=hedgedoc
      - DB_PASS=hedgedoc
      - CMD_DOMAIN=doc.app.quyo.net
      - CMD_HOST=hedgedoc
      - CMD_PROTOCOL_USESSL=true
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_ALLOW_FREEURL=true
      - CMD_REQUIRE_FREEURL_AUTHENTICATION=true
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_DEFAULT_PERMISSION=private
    depends_on:
      - db

  db:
    container_name: hedgedoc_db
    image: linuxserver/mariadb:latest
    volumes:
      - ./config/db:/config
    restart: unless-stopped
    networks:
      - internal
    environment:
      - TZ=Etc/UTC
#     - PGID=1000
#     - PUID=1000
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=hedgedoc

networks:
  proxy:
    external: true
    name: proxy
  internal:
    internal: true
    driver: bridge
