version: '3'
services:
  sagemath:
    container_name: sagemath-dev
#   image: sagemath/sagemath-dev:latest
    image: sagemath/sagemath-dev:develop
    command: /home/sage/sage/docker/entrypoint.sh sage-jupyter --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.notebook_dir='/home/sage/notebooks'
    volumes:
      - ./notebooks:/home/sage/notebooks
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
