version: "2.1"
services:

  privatebin:
    container_name: privatebin
    image: privatebin/nginx-fpm-alpine:latest
    restart: unless-stopped
    read_only: true
    volumes:
      - ./config/conf.php:/srv/cfg/conf.php:ro
      - ./data:/srv/data
    networks:
      - external

networks:
  external:
    name: privatebin_external
