version: "2.1"
services:
  privatebin:
    container_name: privatebin
    image: privatebin/nginx-fpm-alpine:latest
    restart: unless-stopped
    read_only: true
    volumes:
      - ./conf.php:/srv/cfg/conf.php:ro
      - ./data:/srv/data
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
