version: "2.1"
services:

  projectsend:
    container_name: projectsend
    image: lscr.io/linuxserver/projectsend
    volumes:
      - ./config:/config
      - ./data/app:/data
    restart: unless-stopped
    depends_on:
      - projectsend-db
    environment:
      - TZ=Etc/UTC
    networks:
      - external
      - internal

  projectsend-db:
    container_name: projectsend-db
    image: linuxserver/mariadb:latest
    volumes:
      - ./data/db:/config
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=projectsend
      - MYSQL_USER=projectsend
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - internal

networks:
  external:
    name: projectsend_external
  internal:
    name: projectsend_internal
    internal: true
