version: "2.1"
services:

  traccar:
    container_name: traccar
    image: traccar/traccar:latest
    volumes:
      - ./config/traccar.xml:/opt/traccar/conf/traccar.xml
      - ./data/logs:/opt/traccar/logs
    restart: unless-stopped
    depends_on:
      - traccar-db
    ports:
      - 5000-5150:5000-5150/tcp
      - 5000-5150:5000-5150/udp
    networks:
      - external
      - internal

  traccar-db:
    container_name: traccar-db
    image: linuxserver/mariadb:latest
    volumes:
      - ./data/db:/config
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=traccar
      - MYSQL_USER=traccar
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - internal

networks:
  external:
    name: traccar_external
  internal:
    name: traccar_internal
    internal: true
