version: "2.1"
services:
  traccar:
    container_name: traccar
    image: traccar/traccar:latest
    volumes:
      - ./logs:/opt/traccar/logs
      - ./traccar.xml:/opt/traccar/conf/traccar.xml
    restart: unless-stopped
    ports:
      - 5000-5150:5000-5150/tcp
      - 5000-5150:5000-5150/udp
    networks:
      - proxy
      - internal

  db:
    container_name: traccar_db
    image: linuxserver/mariadb:latest
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=traccar
      - MYSQL_USER=traccar
      - MYSQL_PASSWORD=traccar
      - TZ=Etc/UTC

networks:
  proxy:
    external: true
    name: proxy
  internal:
    internal: true
    driver: bridge
