version: '3'
services:
  app:
    image: 'oznu/guacamole:armhf'
    container_name: guacamole
    #ports:
    #  - '8980:8080'
    environment:
      EXTENSIONS: 'auth-totp'
    volumes:
      - ./config:/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
