version: '3.6'
services:
  gitea:
    container_name: gitea
    image: "kunde21/gitea-arm:v1.13.2"
    ports:
      - "2222:22/tcp"
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - USER_UID=1000
      - USER_GID=1000

networks:
  proxy:
    external: true
    name: proxy
