version: "3.5"
services:
  diun:
    container_name: diun
    image: crazymax/diun:latest
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_NOTIF_MAIL_HOST=mail.smtp2go.com"
      - "DIUN_NOTIF_MAIL_PORT=465"
      - "DIUN_NOTIF_MAIL_SSL=true"
      - "DIUN_NOTIF_MAIL_LOCALNAME=${DIUN_NOTIF_MAIL_LOCALNAME}"
      - "DIUN_NOTIF_MAIL_USERNAME=${DIUN_NOTIF_MAIL_USERNAME}"
      - "DIUN_NOTIF_MAIL_PASSWORD=${DIUN_NOTIF_MAIL_PASSWORD}"
      - "DIUN_NOTIF_MAIL_FROM=${DIUN_NOTIF_MAIL_FROM}"
      - "DIUN_NOTIF_MAIL_TO=${DIUN_NOTIF_MAIL_TO}"
    restart: unless-stopped
