version: '3'
services:
  sagemath:
    container_name: cocalc
    image: sagemathinc/cocalc:latest
    volumes:
      - ./projects:/projects
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
