version: "3.5"
services:
  glances:
    container_name: glances
    image: nicolargo/glances:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    pid: host
    networks:
      - proxy
    environment:
      - GLANCES_OPT=-w

networks:
  proxy:
    external: true
    name: proxy
