version: '3'
services:
  sagemath:
    container_name: sagemath
    #image: sagemath/sagemath:latest
    image: sagemath/sagemath:develop
    command: sage-jupyter --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.notebook_dir='/home/sage/notebooks'
    volumes:
      - ./notebooks:/home/sage/notebooks
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
