version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    #command: -H tcp://docker.for.win.localhost:2375
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data:/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
