version: '3'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data:/data
    restart: unless-stopped
    networks:
      - external

networks:
  external:
    name: portainer_external
