version: '2'
services:

  wekan:
    container_name: wekan
    image: quay.io/wekan/wekan
    restart: unless-stopped
    depends_on:
      - wekan-db
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - ROOT_URL=${ROOT_URL}
      #---------------------------------------------------------------
      # ==== EMAIL SETTINGS ====
      # Email settings are required in both MAIL_URL and Admin Panel,
      #   see https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
      #   For SSL in email, change smtp:// to smtps://
      # NOTE: Special characters need to be url-encoded in MAIL_URL.
      #       You can encode those characters for example at: https://www.urlencoder.org
      #- MAIL_URL=smtp://user:pass@mailserver.example.com:25/
      - MAIL_URL=${MAIL_URL}
      - MAIL_FROM=${MAIL_FROM}
      #---------------------------------------------------------------
      # ==== NUMBER OF SEARCH RESULTS PER PAGE BY DEFAULT ====
      #- RESULTS_PER_PAGE=20
      #---------------------------------------------------------------
      # If you disable Wekan API with false, Export Board does not work.
      - WITH_API=true
      #---------------------------------------------------------------
      # ==== RICH TEXT EDITOR IN CARD COMMENTS ====
      # https://github.com/wekan/wekan/pull/2560
      - RICHER_CARD_COMMENT_EDITOR=false
      #---------------------------------------------------------------
      # ==== CARD OPENED, SEND WEBHOOK MESSAGE ====
      # https://github.com/wekan/wekan/issues/2518
      - CARD_OPENED_WEBHOOK_ENABLED=false
      #---------------------------------------------------------------
      # ==== Allow to shrink attached/pasted image ====
      #-MAX_IMAGE_PIXEL=1024
      #-IMAGE_COMPRESS_RATIO=80
      #---------------------------------------------------------------
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    networks:
      - external
      - internal

  wekan-db:
    container_name: wekan-db
    image: mongo:4.4
    restart: unless-stopped
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    volumes:
      - ./data/db:/data/db
      - ./data/db-dump:/dump
    networks:
      - internal

networks:
  external:
    name: wekan_external
  internal:
    name: wekan_internal
    internal: true
