version: "2.1"
services:
  syncthing:
    container_name: syncthing
    image: ghcr.io/linuxserver/syncthing
    hostname: syncthing.predator.ka.quyo.net #optional
    volumes:
      - ./config:/config
      - ./data1:/data1
      - ./data2:/data2
    restart: unless-stopped
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

networks:
  proxy:
    external: true
    name: proxy
