version: "2.1"
services:

  pwndrop:
    container_name: pwndrop
    image: lscr.io/linuxserver/pwndrop
    volumes:
      - ./config:/config
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    networks:
      - external

networks:
  external:
    name: pwndrop_external
