version: "2.1"
services:

  snapdrop:
    container_name: snapdrop
    image: ghcr.io/linuxserver/snapdrop
    volumes:
      - ./config:/config
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    networks:
      - external

networks:
  external:
    name: snapdrop_external
